POST http://localhost:8081/oauth/token
Authorization: Basic Zm9vQ2xpZW50SWRQYXNzd29yZDpzZWNyZXQ=
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache

grant_type=password&password=123&username=john


GET http://localhost:8080/resource1/users/extra
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJqb2huIiwic2NvcGUiOlsiZm9vIiwicmVhZCIsIndyaXRlIl0sIm9yZ2FuaXphdGlvbiI6ImpvaG5wVVNZIiwiZXhwIjoxNTgxNzk5OTY0LCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwianRpIjoiODIxZTE3YjItM2I2NS00NjM1LWI0OGItODdkNTBjY2EzMmYyIiwiY2xpZW50X2lkIjoiZm9vQ2xpZW50SWRQYXNzd29yZCJ9.LGCPMxcZXW_-8HbJgbgz-q_RzTNd-H6NLfAIyRKp4uQ

GET http://localhost:8080/resource/foos/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJqb2huIiwic2NvcGUiOlsiZm9vIiwicmVhZCIsIndyaXRlIl0sIm9yZ2FuaXphdGlvbiI6ImpvaG5vUU5WIiwiZXhwIjoxNTgxNzg5MTY4LCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwianRpIjoiZTVkYTFkNTMtYTZlNy00OWUyLTkxNzItOWQ5NDIxODc5MTNkIiwiY2xpZW50X2lkIjoiZm9vQ2xpZW50SWRQYXNzd29yZCJ9.V-14ZJNg_sfENC5V8c9e2Uuleg8HKDa2BGgKHBAsXlY


POST http://localhost:9000/feignclient/foos
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJqb2huIiwic2NvcGUiOlsiZm9vIiwicmVhZCIsIndyaXRlIl0sIm9yZ2FuaXphdGlvbiI6ImpvaG5YRHdWIiwiZXhwIjoxNTgxODMyNjQ5LCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwianRpIjoiOTQ0ZmM1MzQtN2VhMS00ZDE3LWI2MmEtM2MwNmFlZTFiMmZiIiwiY2xpZW50X2lkIjoiZm9vQ2xpZW50SWRQYXNzd29yZCJ9.UEyBsI_FPBVkf5VTcSsJyhH57SqIME9-LkJOIWB05Go
Content-Type: application/json; charset=utf8

{
    "id":"2",
    "name":"yinuo liu"
}

POST http://localhost:8082/foos
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJqb2huIiwic2NvcGUiOlsiZm9vIiwicmVhZCIsIndyaXRlIl0sIm9yZ2FuaXphdGlvbiI6ImpvaG5YRHdWIiwiZXhwIjoxNTgxODMyNjQ5LCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwianRpIjoiOTQ0ZmM1MzQtN2VhMS00ZDE3LWI2MmEtM2MwNmFlZTFiMmZiIiwiY2xpZW50X2lkIjoiZm9vQ2xpZW50SWRQYXNzd29yZCJ9.UEyBsI_FPBVkf5VTcSsJyhH57SqIME9-LkJOIWB05Go
Content-Type: application/json; charset=utf8

{
    "id":"2",
    "name":"yinuo liu"
}