server:
  port: 8080

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    oauth:
      path: /oauth/**
      serviceId: oauthservice
      stripPrefix: false
    resource:
      path: /resource/**
      serviceId: resource1

spring:
  application:
    name: zuul

security:
  oauth2:
    resource:
      jwt:
        key-value: 123


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true