server:
  port: 8080
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    oauth:
      path: /oauth/**
      serviceId: oauthservice
      stripPrefix: false

  #   spring-security-oauth-resource:
  #     path: /spring-security-oauth-resource/**
  #     url: http://localhost:8082/spring-security-oauth-resource

spring:
  application:
    name: zuul

security:
  oauth2:
    resource:
      jwt:
        key-value: 123


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true